#!/bin/bash
echo "WebJ Script Starts " 
PORTINT=$1
java $JAVA_OPTS -jar target/dependency/webapp-runner.jar --port $PORT --expanded-dir-name WEBJ --expand-war deployments/WebJ.war
#Dont put anything here ...(after deployment)
done

